In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
# combine all 5 csv happiness files into one.
hp2015 = pd.read_csv("csv_files/2015.csv")
hp2016 = pd.read_csv("csv_files/2016.csv")
hp2017 = pd.read_csv("csv_files/2017.csv")
hp2018 = pd.read_csv("csv_files/2018.csv")
hp2019 = pd.read_csv("csv_files/2019.csv")

In [ ]:
#columns wanted:
# 'Country', 'Region', 'Happiness Rank', 'Happiness Score','Standard Error', 'Economy (GDP per Capita)', 'Family',
# 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
# 'Generosity', 'Dystopia Residual'

In [ ]:
# Step 1: cleaning column names
# country column : change 2019 "country or region" to "country" - 'Canada', 'Germany', 'Russia', 'Brazil', 'UK', 'India', 'Australia', 'China', 'USA', 'Japan'
# rank coloum: stadardize column names. use "happiness_rank"
# score coloum: stadardize column names. use "happiness_score"
# Economy (GDP per Capita): standardize column names. use "gdp"
# Trust colomn : standardize column names. use "trust_in_government"
# Step 2: add new column of year.

## HP 2015

In [36]:
hp2015a = hp2015.copy()

In [37]:
hp2015a = hp2015a.drop(columns=['Region', 'Standard Error', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Generosity', 'Dystopia Residual', 'Happiness Rank'])

In [38]:
hp2015a = hp2015a.rename(columns={
    'Country': 'country',
    'Happiness Score': 'happiness_score',
    'Economy (GDP per Capita)': 'gdp',
    'Trust (Government Corruption)': 'trust_in_government',
})

In [68]:
hp2015a['year'] = 2015

In [69]:
hp2015a

         country  happiness_score      gdp  trust_in_government  year
0    Switzerland            7.587  1.39651              0.41978  2015
1        Iceland            7.561  1.30232              0.14145  2015
2        Denmark            7.527  1.32548              0.48357  2015
3         Norway            7.522  1.45900              0.36503  2015
4         Canada            7.427  1.32629              0.32957  2015
..           ...              ...      ...                  ...   ...
153       Rwanda            3.465  0.22208              0.55191  2015
154        Benin            3.340  0.28665              0.08010  2015
155        Syria            3.006  0.66320              0.18906  2015
156      Burundi            2.905  0.01530              0.10062  2015
157         Togo            2.839  0.20868              0.10731  2015

[158 rows x 5 columns]

## HP 2016

In [41]:
hp2016a = hp2016.copy()

In [42]:
hp2016a

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [43]:
hp2016a = hp2016a.drop(columns=['Region','Lower Confidence Interval','Upper Confidence Interval', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Generosity', 'Dystopia Residual', 'Happiness Rank'])

In [44]:
hp2016a = hp2016a.rename(columns={
    'Country': 'country',
    'Happiness Score': 'happiness_score',
    'Economy (GDP per Capita)': 'gdp',
    'Trust (Government Corruption)': 'trust_in_government',
})

In [70]:
hp2016a['year'] = 2016

In [71]:
hp2016a

         country  happiness_score      gdp  trust_in_government  year
0        Denmark            7.526  1.44178              0.44453  2016
1    Switzerland            7.509  1.52733              0.41203  2016
2        Iceland            7.501  1.42666              0.14975  2016
3         Norway            7.498  1.57744              0.35776  2016
4        Finland            7.413  1.40598              0.41004  2016
..           ...              ...      ...                  ...   ...
152        Benin            3.484  0.39499              0.06681  2016
153  Afghanistan            3.360  0.38227              0.07112  2016
154         Togo            3.303  0.28123              0.11587  2016
155        Syria            3.069  0.74719              0.17233  2016
156      Burundi            2.905  0.06831              0.09419  2016

[157 rows x 5 columns]

## HP 2017

In [89]:
hp2017a = hp2017.copy()

In [90]:
hp2017a

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [91]:
hp2017a = hp2017a.drop(columns=['Whisker.high','Whisker.low', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Dystopia.Residual', 'Happiness.Rank'])

In [92]:
hp2017a = hp2017a.rename(columns={
    'Country': 'country',
    'Happiness.Score': 'happiness_score',
    'Economy..GDP.per.Capita.': 'gdp',
    'Trust..Government.Corruption.': 'trust_in_government',
})

In [93]:
hp2017a['year'] = 2017

In [94]:
hp2017a

,country,happiness_score,gdp,trust_in_government,year
0,Norway,7.537,1.616463,0.315964,2017
1,Denmark,7.522,1.482383,0.400770,2017
2,Iceland,7.504,1.480633,0.153527,2017
3,Switzerland,7.494,1.564980,0.367007,2017
4,Finland,7.469,1.443572,0.382612,2017
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.455220,2017
151,Syria,3.462,0.777153,0.151347,2017
152,Tanzania,3.349,0.511136,0.066035,2017
153,Burundi,2.905,0.091623,0.084148,2017
154,Central African Republic,2.693,0.000000,0.056565,2017

## HP 2018

In [55]:
hp2018a = hp2018.copy()

In [56]:
hp2018a

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...
151,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

In [57]:
hp2018a = hp2018a.drop(columns=['Overall rank','Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy'])

In [58]:
hp2018a = hp2018a.rename(columns={
    'Country or region': 'country',
    'Score': 'happiness_score',
    'GDP per capita': 'gdp',
    'Perceptions of corruption': 'trust_in_government',
})

In [67]:
hp2018a

                      country  happiness_score    gdp  trust_in_government
0                     Finland            7.632  1.305                0.393
1                      Norway            7.594  1.456                0.340
2                     Denmark            7.555  1.351                0.408
3                     Iceland            7.495  1.343                0.138
4                 Switzerland            7.487  1.420                0.357
..                        ...              ...    ...                  ...
151                     Yemen            3.355  0.442                0.064
152                  Tanzania            3.303  0.455                0.097
153               South Sudan            3.254  0.337                0.106
154  Central African Republic            3.083  0.024                0.038
155                   Burundi            2.905  0.091                0.076

[156 rows x 4 columns]

In [76]:
hp2018a['year'] = 2018

In [77]:
hp2018a

,country,happiness_score,gdp,trust_in_government,year
0,Finland,7.632,1.305,0.393,2018
1,Norway,7.594,1.456,0.340,2018
2,Denmark,7.555,1.351,0.408,2018
3,Iceland,7.495,1.343,0.138,2018
4,Switzerland,7.487,1.420,0.357,2018
...,...,...,...,...,...
151,Yemen,3.355,0.442,0.064,2018
152,Tanzania,3.303,0.455,0.097,2018
153,South Sudan,3.254,0.337,0.106,2018
154,Central African Republic,3.083,0.024,0.038,2018
155,Burundi,2.905,0.091,0.076,2018

## HP 2019

In [60]:
hp2019a = hp2019.copy()

In [62]:
hp2019a

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [63]:
hp2019a = hp2019a.drop(columns=['Overall rank','Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy'])

In [65]:
hp2019a = hp2019a.rename(columns={
    'Country or region': 'country',
    'Score': 'happiness_score',
    'GDP per capita': 'gdp',
    'Perceptions of corruption': 'trust_in_government',
})

In [78]:
hp2019a['year'] = 2019

In [79]:
hp2019a

,country,happiness_score,gdp,trust_in_government,year
0,Finland,7.769,1.340,0.393,2019
1,Denmark,7.600,1.383,0.410,2019
2,Norway,7.554,1.488,0.341,2019
3,Iceland,7.494,1.380,0.118,2019
4,Netherlands,7.488,1.396,0.298,2019
...,...,...,...,...,...
151,Rwanda,3.334,0.359,0.411,2019
152,Tanzania,3.231,0.476,0.147,2019
153,Afghanistan,3.203,0.350,0.025,2019
154,Central African Republic,3.083,0.026,0.035,2019
155,South Sudan,2.853,0.306,0.091,2019

## DataSets Concact

In [ ]:
""""
hp2019a
hp2018a
hp2017a
hp2016a
hp2015a

""""

In [95]:
hp_2015_2019 = pd.concat([hp2015a, hp2016a, hp2017a, hp2018a, hp2019a], axis=0)

In [ ]:
hp_2015_2019.reindex['country', 'year', 'happiness_score', 'gdp', 'trust_in_government']

In [98]:
hp_2015_2019

,country,happiness_score,gdp,trust_in_government,year
0,Switzerland,7.587,1.39651,0.41978,2015
1,Iceland,7.561,1.30232,0.14145,2015
2,Denmark,7.527,1.32548,0.48357,2015
3,Norway,7.522,1.45900,0.36503,2015
4,Canada,7.427,1.32629,0.32957,2015
...,...,...,...,...,...
151,Rwanda,3.334,0.35900,0.41100,2019
152,Tanzania,3.231,0.47600,0.14700,2019
153,Afghanistan,3.203,0.35000,0.02500,2019
154,Central African Republic,3.083,0.02600,0.03500,2019
155,South Sudan,2.853,0.30600,0.09100,2019